name: Pick Random Reviwer
on:
    pull_request:
        branches:
            - master
            - main
jobs:
  pick-random-reviwer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
           
      - name: pick_random_reviwer
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |

            const candidate = ['parkjisu6239', 'parkjisu6239', 'parkjisu6239'];
            const randomReviewer = candidate[Math.floor(Math.random() * candidate.length)];
            
            const comment = `@${randomReviewer} 님 랜덤 리뷰어로 당첨되셨습니다.`
            core.setOutput('comment', comment)
            core.setOutput('reviewer', randomReviewer)

      - name: comment PR
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{ steps.pick_random_reviwer.outputs.comment }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          
      - name: Add Pull Request Reviewer
          uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
          with: 
            reviewers: ${{ steps.pick_random_reviwer.outputs.reviewer }}
            token: ${{ secrets.GITHUB_TOKEN }}
